apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: job_apply-php:latest # Substitua pelo caminho da sua imagem
#        image: docker.io/library/job_apply-php:latest
#        image: localhost:5000/job_apply-php:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: php-secrets
        - configMapRef:
            name: php-config
        volumeMounts:
        - name: php-src
          mountPath: /var/www/html
      volumes:
      - name: php-src
        hostPath:
          path: /home/chateau/win/job_apply/php/src
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php
