#version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  php:
    build:
      context: ./php
    container_name: php_container
    restart: always
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./php/src:/var/www/html
      - ./env:/var/env
    environment:
      # Não está lendo a variavel abaixo ao subir o docker
#     PHP_ERROR_REPORTING: "E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED"
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

volumes:
  db_data:
